version: "0.16.0"

formatter: "markdown table"

output:
  file: "README.md"
  mode: "inject"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

recursive:
  enabled: true
  path: "modules"
  output:
    file: "README.md"

file-patterns:
  - "*.tf"
  - "*.tfvars"

exclude:
  - "*.zip"
  - "*.json"
  - "*.tpl"
  - "backend/*"
  - "**/terraform.tfstate*"

sections:
  hide:
    - "providers"
    - "requirements"
  show:
    - "header"
    - "inputs"
    - "outputs"
    - "modules"

sort:
  enabled: true
  by: "name"

settings:
  anchor: false
  color: false
  default: true
  description: true
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true